//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexMultiplicationFlashCards.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public int Response { get; set; }
        public int RoundId { get; set; }
        public int FlashCardId { get; set; }
    
        public virtual FlashCard FlashCard { get; set; }
        public virtual Round Round { get; set; }
    }
}
